version: '3.8'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      timeout: 5s
      retries: 3

  api:
    image: craftsiteapi
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - craftsiteapi:latest
    environment:
      WAIT_HOSTS: db:3306
      NODE_ENV: production
      JWT_SECRET: 'DJk&&*$BKDJSI^&@GKD<JKDSLK*@%'
      DATABASE_URL: 'mysql://root:root@db:3306/craft'
      ORIGIN_URL: 'http://localhost:3000'
    command: sh -c "/wait && /migration.sh"
    ports:
      - '3005:3005'
    depends_on:
      - db

volumes:
  db_data:
